# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gradIPS <- function(b, d, X, w, treated_flag, whs) {
    .Call(`_IPS_gradIPS`, b, d, X, w, treated_flag, whs)
}

gradLIPS <- function(b, d, z, X, w, whs) {
    .Call(`_IPS_gradLIPS`, b, d, z, X, w, whs)
}

linIPS <- function(bhat, d, pshat, X, w, treated_flag, whs) {
    .Call(`_IPS_linIPS`, bhat, d, pshat, X, w, treated_flag, whs)
}

linLIPS <- function(bhat, d, z, ipshat, X, w, whs) {
    .Call(`_IPS_linLIPS`, bhat, d, z, ipshat, X, w, whs)
}

objIPS <- function(b, d, X, w, treated_flag, whs) {
    .Call(`_IPS_objIPS`, b, d, X, w, treated_flag, whs)
}

objLIPS <- function(b, d, z, X, w, whs) {
    .Call(`_IPS_objLIPS`, b, d, z, X, w, whs)
}

weightIPSexp <- function(X, X_trans) {
    .Call(`_IPS_weightIPSexp`, X, X_trans)
}

weightIPSind <- function(X) {
    .Call(`_IPS_weightIPSind`, X)
}

weightIPSproj <- function(X) {
    .Call(`_IPS_weightIPSproj`, X)
}

weightIPSproj_vec <- function(X) {
    .Call(`_IPS_weightIPSproj_vec`, X)
}

